Pages/Biserici/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Pages.Biserici
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public CreateModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Biserica Biserica { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Biserica == null || Biserica == null)
            {
                return Page();
            }

            _context.Biserica.Add(Biserica);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Biserici/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Pages.Biserici
{
    [Authorize(Roles = "Admin")]
    public class DeleteModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public DeleteModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Biserica Biserica { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Biserica == null)
            {
                return NotFound();
            }

            var biserica = await _context.Biserica.FirstOrDefaultAsync(m => m.ID == id);

            if (biserica == null)
            {
                return NotFound();
            }
            else 
            {
                Biserica = biserica;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Biserica == null)
            {
                return NotFound();
            }
            var biserica = await _context.Biserica.FindAsync(id);

            if (biserica != null)
            {
                Biserica = biserica;
                _context.Biserica.Remove(Biserica);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Biserici/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Pages.Biserici
{
    public class DetailsModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public DetailsModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

      public Biserica Biserica { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Biserica == null)
            {
                return NotFound();
            }

            var biserica = await _context.Biserica.FirstOrDefaultAsync(m => m.ID == id);
            if (biserica == null)
            {
                return NotFound();
            }
            else 
            {
                Biserica = biserica;
            }
            return Page();
        }
    }
}

Pages/Biserici/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Pages.Biserici
{
    [Authorize(Roles = "Admin")]
    public class EditModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public EditModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Biserica Biserica { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Biserica == null)
            {
                return NotFound();
            }

            var biserica =  await _context.Biserica.FirstOrDefaultAsync(m => m.ID == id);
            if (biserica == null)
            {
                return NotFound();
            }
            Biserica = biserica;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Biserica).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!BisericaExists(Biserica.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool BisericaExists(int id)
        {
          return (_context.Biserica?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Pages/Enoriasi/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Pages.Enoriasi
{
    public class CreateModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public CreateModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Enorias Enorias { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Enorias == null || Enorias == null)
            {
                return Page();
            }

            _context.Enorias.Add(Enorias);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Enoriasi/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Pages.Enoriasi
{
    public class DeleteModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public DeleteModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Enorias Enorias { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Enorias == null)
            {
                return NotFound();
            }

            var enorias = await _context.Enorias.FirstOrDefaultAsync(m => m.ID == id);

            if (enorias == null)
            {
                return NotFound();
            }
            else 
            {
                Enorias = enorias;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Enorias == null)
            {
                return NotFound();
            }
            var enorias = await _context.Enorias.FindAsync(id);

            if (enorias != null)
            {
                Enorias = enorias;
                _context.Enorias.Remove(Enorias);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Enoriasi/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Pages.Enoriasi
{
    public class DetailsModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public DetailsModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

      public Enorias Enorias { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Enorias == null)
            {
                return NotFound();
            }

            var enorias = await _context.Enorias.FirstOrDefaultAsync(m => m.ID == id);
            if (enorias == null)
            {
                return NotFound();
            }
            else 
            {
                Enorias = enorias;
            }
            return Page();
        }
    }
}

Pages/Enoriasi/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;

namespace Proiect.Pages.Enoriasi
{
    public class EditModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public EditModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Enorias Enorias { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Enorias == null)
            {
                return NotFound();
            }

            var enorias =  await _context.Enorias.FirstOrDefaultAsync(m => m.ID == id);
            if (enorias == null)
            {
                return NotFound();
            }
            Enorias = enorias;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Enorias).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EnoriasExists(Enorias.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool EnoriasExists(int id)
        {
          return (_context.Enorias?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Pages/Preoti/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Proiect.Data;
using Proiect.Models;




namespace Proiect.Pages.Preoti
{
    [Authorize(Roles = "Admin")]
    public class CreateModel : PageModel
    {
        private readonly Proiect.Data.ProiectContext _context;

        public CreateModel(Proiect.Data.ProiectContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Preot Preot { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Preot == null || Preot == null)
            {
                return Page();
            }

            _context.Preot.Add(Preot);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Programari/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Proiect.Data;
using Proiect.Models;
using Stripe.Checkout;
using Stripe;
using Microsoft.Extensions.Options;
using Proiect.Migrations;
using Proiect.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace Proiect.Pages.Programari
{
    public class IndexModel : PageModel
    {
        private readonly ProiectContext _context;
        private readonly StripeSettings _stripeSettings;
        public string SessionId { get; set; }

        public IndexModel(ProiectContext context, IOptions<StripeSettings> stripeSettings)
        {
            _stripeSettings = stripeSettings.Value;
            _context = context;
        }

        public IList<Programare> Programari { get; set; } = default!;

        public async Task OnGetAsync()
        {

            var isAdmin = User.IsInRole("Admin");

            if (_context.Programare != null)
            {
                try
                {

                    if (isAdmin)
                    {
                        Programari = await _context.Programare
                        .Include(p => p.Biserica)
                        .Include(p => p.Enorias)
                        .Include(p => p.Preot)
                        .Include(p => p.Serviciu)
                        .ToListAsync();

                    }
                    else
                    {
                        var userEmail = User.FindFirstValue(ClaimTypes.Email);
                        if (userEmail != null)
                        {
                            Programari = await _context.Programare
                           .Include(p => p.Biserica)
                           .Include(p => p.Enorias)
                           .Include(p => p.Preot)
                           .Include(p => p.Serviciu)
                           .Where(p => p.Enorias.Email == userEmail)
                           .ToListAsync();
                        }
                        else
                        {
                            Programari = new List<Programare>();
                        }
                    }

                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Error loading Programari: {ex.Message}");
                    throw;
                }
            }
        }

        public IActionResult OnPostCreateCheckoutSession(string amount)
        {
            var currency = "ron";

            var successUrl = "https://localhost:7044/";
            var cancelUrl = "https://localhost:7044/";

            StripeConfiguration.ApiKey = _stripeSettings.SecretKey;

            if (decimal.TryParse(amount, out decimal amountValue))
            {
                var options = new SessionCreateOptions
                {
                    PaymentMethodTypes = new List<string> { "card" },
                    LineItems = new List<SessionLineItemOptions>
            {
                new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        Currency = currency,
                        UnitAmount = (long)(amountValue * 100),
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = "Product Name",
                            Description = "Product Description"
                        }
                    },
                    Quantity = 1
                }
            },
                    Mode = "payment",
                    SuccessUrl = successUrl,
                    CancelUrl = cancelUrl,
                };

                var service = new SessionService();
                var session = service.Create(options);
                SessionId = session.Id;

                return Redirect(session.Url);
            }
            else
            {
                Console.WriteLine($"Valore invalida: {amount}");
                return RedirectToPage("/Error");
            }
        }

    }
}

Pages/Programari/Create.cshtml
@page
@model Proiect.Pages.Programari.CreateModel


@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Programari</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Programare.EnoriasID" class="control-label"></label>
                <select asp-for="Programare.EnoriasID" class="form-control" asp-items="ViewBag.EnoriasID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Programare.PreotID" class="control-label"></label>
                <select asp-for="Programare.PreotID" class="form-control" asp-items="ViewBag.PreotID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Programare.ServiciuID" class="control-label"></label>
                <select asp-for="Programare.ServiciuID" class="form-control" asp-items="ViewBag.ServiciuID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Programare.BisericaID" class="control-label"></label>
                <select asp-for="Programare.BisericaID" class="form-control" asp-items="ViewBag.BisericaID"></select>
            </div>
            <div class="form-group">
                <label asp-for="Programare.DataProgramare" class="control-label"></label>
                <input asp-for="Programare.DataProgramare" class="form-control" />
                <span asp-validation-for="Programare.DataProgramare" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Pages/Programari/Delete.cshtml
@page
@model Proiect.Pages.Programari.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Programare</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.Enorias)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.Enorias.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.Preot)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.Preot.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.Serviciu)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.Serviciu.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.Biserica)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.Biserica.ID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.DataProgramare)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.DataProgramare)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Programare.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/Programari/Details.cshtml
@page
@model Proiect.Pages.Programari.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Programare</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.Enorias)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.Enorias.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.Preot)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.Preot.FullName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.Serviciu)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.Serviciu.NumeServiciu)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.Biserica)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.Biserica.Nume)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Programare.DataProgramare)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Programare.DataProgramare)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Programare?.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/Programari/Edit.cshtml
@page
@model Proiect.Pages.Programari.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Programare</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Programare.ID" />
            <div class="form-group">
                <label asp-for="Programare.EnoriasID" class="control-label"></label>
                <select asp-for="Programare.EnoriasID" class="form-control" asp-items="ViewBag.EnoriasID"></select>
                <span asp-validation-for="Programare.EnoriasID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programare.PreotID" class="control-label"></label>
                <select asp-for="Programare.PreotID" class="form-control" asp-items="ViewBag.PreotID"></select>
                <span asp-validation-for="Programare.PreotID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programare.ServiciuID" class="control-label"></label>
                <select asp-for="Programare.ServiciuID" class="form-control" asp-items="ViewBag.ServiciuID"></select>
                <span asp-validation-for="Programare.ServiciuID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programare.BisericaID" class="control-label"></label>
                <select asp-for="Programare.BisericaID" class="form-control" asp-items="ViewBag.BisericaID"></select>
                <span asp-validation-for="Programare.BisericaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Programare.DataProgramare" class="control-label"></label>
                <input asp-for="Programare.DataProgramare" class="form-control" />
                <span asp-validation-for="Programare.DataProgramare" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Programari/Index.cshtml
@page
@model Proiect.Pages.Programari.IndexModel

@{
    ViewData["Title"] = "Programari";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Programari</h1>

<p>
    <a asp-page="Create">Creeaza o programare</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Programari[0].Enorias)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programari[0].Preot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programari[0].Serviciu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programari[0].Biserica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programari[0].DataProgramare)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Programari) {
        <tr>
            <td>

                        @if (item.Enorias != null && item.Enorias.FullName != null)
                        {
                            @Html.DisplayFor(modelItem => item.Enorias.FullName)
                        }
                       
            </td>
            <td> @if (item.Preot != null && item.Preot.FullName != null)
                {
                            @Html.DisplayFor(modelItem => item.Preot.FullName)
                        }
                        
            </td>
            <td>

                        @if (item.Serviciu != null && item.Serviciu.NumeServiciu != null)
                        {
                            @Html.DisplayFor(modelItem => item.Serviciu.NumeServiciu)
                        }
                       
            </td>
            <td>
                        @if (item.Biserica != null && item.Biserica.Nume != null)
                        {
                            @Html.DisplayFor(modelItem => item.Biserica.Nume)
                        }
                       
            </td>
            <td>

                @Html.DisplayFor(modelItem => item.DataProgramare)
            </td>

            <td>
                <a asp-page="./Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.ID">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>


                    <div>
                    <h1>Total de plata: @(item.Serviciu != null ? Html.DisplayFor(modelItem => item.Serviciu.PretServiciu) : null)</h1>


                        
                    
                        <form method="post" asp-page-handler="CreateCheckoutSession" asp-route-amount="@item.Serviciu.PretServiciu">
                            <button type="submit" class="btn btn-warning" style="background-color: #FFA07A; border-color: #FFA07A; color: black; margin-left: 100px">Achita programarea</button>
                        </form>


                    </div>


                    
                        

            </td>
        </tr>
}
    </tbody>
</table>

Pages/Programari/SuccessPage.cshtml
@page
@model Proiect.Pages.Programari.SuccessPageModel
@{


    <h1> Plata a fost realizata cu success</h1>
}